In [1]:
from database_connect import mongo_operation as mongo

client_url= "mongodb+srv://hrisikesh:hrisikeshAndineuron@cluster0.iq9nlei.mongodb.net/?retryWrites=true&w=majority"
database_name = "sensor"


def upload_files_to_mongodb(
    mongo_client_con_string,
    database_name,
    datasets_dir_name):
  
  for file in os.listdir(datasets_dir_name):
    if file.endswith('.csv'):
      file_name = file.split('.')[0]

      mongo_connection = mongo(
          client_url = mongo_client_con_string,
          database_name= database_name,
          collection_name= file_name
      )

      file_path = os.path.join(datasets_dir_name, file_name)
      mongo_connection.bulk_insert(file)
      print(f"{file_name} is uploaded to mongodb")


upload_files_to_mongodb(
    mongo_client_con_string= client_url,
    database_name = database_name,
    datasets_dir_name= "/content"
)

ModuleNotFoundError: No module named 'database_connect'

In [2]:
pip install pandas

Collecting pandas
  Obtaining dependency information for pandas from https://files.pythonhosted.org/packages/c3/6c/ea362eef61f05553aaf1a24b3e96b2d0603f5dc71a3bd35688a24ed88843/pandas-2.0.3-cp38-cp38-win_amd64.whl.metadata
  Using cached pandas-2.0.3-cp38-cp38-win_amd64.whl.metadata (18 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in e:\mlproject\sensor-fault-detection\.conda\lib\site-packages (from pandas) (2.8.2)
Collecting pytz>=2020.1 (from pandas)
  Obtaining dependency information for pytz>=2020.1 from https://files.pythonhosted.org/packages/32/4d/aaf7eff5deb402fd9a24a1449a8119f00d74ae9c2efa79f8ef9994261fc2/pytz-2023.3.post1-py2.py3-none-any.whl.metadata
  Using cached pytz-2023.3.post1-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.1 (from pandas)
  Using cached tzdata-2023.3-py2.py3-none-any.whl (341 kB)
Collecting numpy>=1.20.3 (from pandas)
  Obtaining dependency information for numpy>=1.20.3 from https://files.pythonhosted.org/packages/69/65/0d47953afa0ad569d12de5f65d964321c208492064c38fe3b0b9744f8d44/numpy-1.24.4-cp38-cp38-win_amd64.whl.metadata
  Using cached numpy-1.24.4-cp38-cp38-win_amd64.whl.metadata (5.6 kB)
Requirement already satisfied: six>=1.5 in e:\mlproject\sensor-fault-detection\.conda\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Using cached pandas-2.0.3-cp38-cp38-win_amd64.whl (10.8 MB)
Using cached numpy-1.24.4-cp38-cp38-win_amd64.whl (14.9 MB)
Using cached pytz-2023.3.post1-py2.py3-none-any.whl (502 kB)
Installing collected packages: pytz, tzdata, numpy, pandas
Successfully installed numpy-1.24.4 pandas-2.0.3 pytz-2023.3.post1 tzdata-2023.3
Note: you may need to restart the kernel to use updated packages.

In [4]:
pip install pymongo

Collecting pymongo
  Obtaining dependency information for pymongo from https://files.pythonhosted.org/packages/e1/05/fd245fa1e2fdab20f136b72df19cc5301f3dba50e5bcf63220cffacad2f8/pymongo-4.5.0-cp38-cp38-win_amd64.whl.metadata
  Using cached pymongo-4.5.0-cp38-cp38-win_amd64.whl.metadata (22 kB)
Collecting dnspython<3.0.0,>=1.16.0 (from pymongo)
  Obtaining dependency information for dnspython<3.0.0,>=1.16.0 from https://files.pythonhosted.org/packages/f6/b4/0a9bee52c50f226a3cbfb54263d02bb421c7f2adc136520729c2c689c1e5/dnspython-2.4.2-py3-none-any.whl.metadata
  Downloading dnspython-2.4.2-py3-none-any.whl.metadata (4.9 kB)
Downloading pymongo-4.5.0-cp38-cp38-win_amd64.whl (467 kB)
   ---------------------------------------- 0.0/468.0 kB ? eta -:--:--
    --------------------------------------- 10.2/468.0 kB ? eta -:--:--
    --------------------------------------- 10.2/468.0 kB ? eta -:--:--
   --- ----------------------------------- 41.0/468.0 kB 281.8 kB/s eta 0:00:02
   ----- --------------------------------- 71.7/468.0 kB 438.9 kB/s eta 0:00:01
   --------- ---------------------------- 122.9/468.0 kB 602.4 kB/s eta 0:00:01
   ---------------- --------------------- 204.8/468.0 kB 831.5 kB/s eta 0:00:01
   ------------------------ ------------- 307.2/468.0 kB 999.9 kB/s eta 0:00:01
   -------------------------------------- - 450.6/468.0 kB 1.3 MB/s eta 0:00:01
   ---------------------------------------- 468.0/468.0 kB 1.2 MB/s eta 0:00:00
Downloading dnspython-2.4.2-py3-none-any.whl (300 kB)
   ---------------------------------------- 0.0/300.4 kB ? eta -:--:--
   ---------------- ----------------------- 122.9/300.4 kB 2.4 MB/s eta 0:00:01
   --------------------------- ------------ 204.8/300.4 kB 2.5 MB/s eta 0:00:01
   ---------------------------------------- 300.4/300.4 kB 1.9 MB/s eta 0:00:00
Installing collected packages: dnspython, pymongo
Successfully installed dnspython-2.4.2 pymongo-4.5.0
Note: you may need to restart the kernel to use updated packages.

In [5]:
import pandas as pd
import json
from pymongo.mongo_client import MongoClient

In [25]:
#uniform resource identifier

uri = "mongodb+srv://syedzaid0911:Syedzaid0911@cluster0.28po1ro.mongodb.net/?retryWrites=true&w=majority"

In [26]:
client = MongoClient(uri)

In [27]:
##create database name and collection name
DATABASE_NAME="pwskills"
COLLECTION_NAME="waferfault"

In [28]:
# read the data as a dataframe
df=pd.read_csv(r"E:\MLProject\sensor-fault-detection\notebooks\wafer_23012020_041211 (1).csv")

In [29]:
df

,Unnamed: 0,Sensor-1,Sensor-2,Sensor-3,Sensor-4,Sensor-5,Sensor-6,Sensor-7,Sensor-8,Sensor-9,...,Sensor-582,Sensor-583,Sensor-584,Sensor-585,Sensor-586,Sensor-587,Sensor-588,Sensor-589,Sensor-590,Good/Bad
0,Wafer-801,2968.33,2476.58,2216.7333,1748.0885,1.1127,100.0,97.5822,0.1242,1.5300,...,NaN,0.5004,0.0120,0.0033,2.4069,0.0545,0.0184,0.0055,33.7876,-1
1,Wafer-802,2961.04,2506.43,2170.0666,1364.5157,1.5447,100.0,96.7700,0.1230,1.3953,...,NaN,0.4994,0.0115,0.0031,2.3020,0.0545,0.0184,0.0055,33.7876,1
2,Wafer-803,3072.03,2500.68,2205.7445,1363.1048,1.0518,100.0,101.8644,0.1220,1.3896,...,NaN,0.4987,0.0118,0.0036,2.3719,0.0545,0.0184,0.0055,33.7876,-1
3,Wafer-804,3021.83,2419.83,2205.7445,1363.1048,1.0518,100.0,101.8644,0.1220,1.4108,...,NaN,0.4934,0.0123,0.0040,2.4923,0.0545,0.0184,0.0055,33.7876,-1
4,Wafer-805,3006.95,2435.34,2189.8111,1084.6502,1.1993,100.0,104.8856,0.1234,1.5094,...,NaN,0.4987,0.0145,0.0041,2.8991,0.0545,0.0184,0.0055,33.7876,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,Wafer-896,3013.66,2526.44,2185.2111,1141.6306,0.8447,100.0,100.5978,0.1217,1.5337,...,NaN,0.5013,0.0076,0.0021,1.5152,0.0153,0.0048,0.0017,31.0176,-1
96,Wafer-897,2982.87,2477.01,2315.2667,2360.1325,1.1259,100.0,90.1144,0.1160,1.4695,...,NaN,0.5003,0.0106,0.0028,2.1263,0.0153,0.0048,0.0017,31.0176,1
97,Wafer-898,3084.82,2387.42,2171.5000,1028.4440,0.7899,100.0,101.5122,0.1224,1.3603,...,NaN,0.5016,0.0130,0.0028,2.5865,0.0153,0.0048,0.0017,31.0176,-1
98,Wafer-899,2955.87,2541.89,NaN,NaN,NaN,NaN,NaN,NaN,1.4493,...,NaN,0.5023,0.0140,0.0033,2.7810,0.0153,0.0048,0.0017,31.0176,-1
99,Wafer-900,2914.86,2465.11,2210.2778,2120.5760,1.0700,100.0,95.1089,0.1230,1.5817,...,NaN,0.5026,0.0121,0.0032,2.4064,0.0153,0.0048,0.0017,31.0176,1

In [30]:
df=df.drop("Unnamed: 0",axis=1)

In [31]:
df

,Sensor-1,Sensor-2,Sensor-3,Sensor-4,Sensor-5,Sensor-6,Sensor-7,Sensor-8,Sensor-9,Sensor-10,...,Sensor-582,Sensor-583,Sensor-584,Sensor-585,Sensor-586,Sensor-587,Sensor-588,Sensor-589,Sensor-590,Good/Bad
0,2968.33,2476.58,2216.7333,1748.0885,1.1127,100.0,97.5822,0.1242,1.5300,-0.0279,...,NaN,0.5004,0.0120,0.0033,2.4069,0.0545,0.0184,0.0055,33.7876,-1
1,2961.04,2506.43,2170.0666,1364.5157,1.5447,100.0,96.7700,0.1230,1.3953,0.0084,...,NaN,0.4994,0.0115,0.0031,2.3020,0.0545,0.0184,0.0055,33.7876,1
2,3072.03,2500.68,2205.7445,1363.1048,1.0518,100.0,101.8644,0.1220,1.3896,0.0138,...,NaN,0.4987,0.0118,0.0036,2.3719,0.0545,0.0184,0.0055,33.7876,-1
3,3021.83,2419.83,2205.7445,1363.1048,1.0518,100.0,101.8644,0.1220,1.4108,-0.0046,...,NaN,0.4934,0.0123,0.0040,2.4923,0.0545,0.0184,0.0055,33.7876,-1
4,3006.95,2435.34,2189.8111,1084.6502,1.1993,100.0,104.8856,0.1234,1.5094,-0.0046,...,NaN,0.4987,0.0145,0.0041,2.8991,0.0545,0.0184,0.0055,33.7876,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,3013.66,2526.44,2185.2111,1141.6306,0.8447,100.0,100.5978,0.1217,1.5337,0.0090,...,NaN,0.5013,0.0076,0.0021,1.5152,0.0153,0.0048,0.0017,31.0176,-1
96,2982.87,2477.01,2315.2667,2360.1325,1.1259,100.0,90.1144,0.1160,1.4695,0.0071,...,NaN,0.5003,0.0106,0.0028,2.1263,0.0153,0.0048,0.0017,31.0176,1
97,3084.82,2387.42,2171.5000,1028.4440,0.7899,100.0,101.5122,0.1224,1.3603,-0.0031,...,NaN,0.5016,0.0130,0.0028,2.5865,0.0153,0.0048,0.0017,31.0176,-1
98,2955.87,2541.89,NaN,NaN,NaN,NaN,NaN,NaN,1.4493,-0.0194,...,NaN,0.5023,0.0140,0.0033,2.7810,0.0153,0.0048,0.0017,31.0176,-1
99,2914.86,2465.11,2210.2778,2120.5760,1.0700,100.0,95.1089,0.1230,1.5817,0.0118,...,NaN,0.5026,0.0121,0.0032,2.4064,0.0153,0.0048,0.0017,31.0176,1

In [32]:
json_records=list(json.loads(df.T.to_json()).values())

In [ ]:
# convert the data as a json
json_records=json.loads(df.T.to_json)

In [33]:
# now dump the data into the database
client[DATABASE_NAME][COLLECTION_NAME].insert_many(json_records)